version: "3"
services:
  api:
    container_name: api
    build: backend/.
    ports:
      - 3000:3000
    environment:
      POSTGRES_HOST: postgres:mysecretpassword@postgres:5432
      PORT: 3000
    depends_on:
      - postgres
    links:
      - postgres

  postgres:
    container_name: postgres
    restart: always
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: maniacforum2

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    container_name: frontend
    volumes:
      - ./frontend:/usr/src/app/maniacforum2
      - /usr/src/app/maniacforum2/node_modules
    depends_on:
      - api
