-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


-- create tables
CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    username character varying NOT NULL,
    password character varying NOT NULL,
    firstname character varying,
    lastname character varying,
    email character varying NOT NULL,
    showname boolean,
    residence character varying,
    homepage character varying,
    firstgame character varying,
    genres text,
    systems text,
    classics text,
    hobbies text,
    id_xbox character varying,
    id_ps character varying,
    id_nintendo character varying,
    image character varying,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.boards
(
    id serial NOT NULL,
    title character varying NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.threads
(
    board_id integer NOT NULL,
    id serial NOT NULL,
    title character varying,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.msgs
(
    thread_id integer NOT NULL,
    id serial NOT NULL,
    user_id integer NOT NULL,
    parent_id integer,
    parent_user_id integer,
    "timestamp" timestamp without time zone NOT NULL,
    PRIMARY KEY (id)
);

-- create references
ALTER TABLE public.threads
    ADD FOREIGN KEY (board_id)
    REFERENCES public.boards (id)
    NOT VALID;


ALTER TABLE public.msgs
    ADD FOREIGN KEY (thread_id)
    REFERENCES public.threads (id)
    NOT VALID;


ALTER TABLE public.msgs
    ADD FOREIGN KEY (parent_id)
    REFERENCES public.msgs (id)
    NOT VALID;


ALTER TABLE public.msgs
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.msgs
    ADD FOREIGN KEY (parent_user_id)
    REFERENCES public.users (id)
    NOT VALID;

END;

-- create boards
INSERT INTO boards VALUES (DEFAULT, 'Smalltalk');
INSERT INTO boards VALUES (DEFAULT, 'For Sale');
INSERT INTO boards VALUES (DEFAULT, 'Tech''n''Cheats');
INSERT INTO boards VALUES (DEFAULT, 'OT');
INSERT INTO boards VALUES (DEFAULT, 'Filme & Serien');
INSERT INTO boards VALUES (DEFAULT, 'Corona');
INSERT INTO boards VALUES (DEFAULT, 'Online');