-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.users
(
    id serial NOT NULL,
    username character varying(64) NOT NULL,
    password character varying(64) NOT NULL,
    first_name character varying(64),
    last_name character varying(64),
    email character varying(64) NOT NULL,
    show_name boolean,
    residence character varying(128),
    homepage character varying(128),
    first_game character varying(128),
    genres text,
    systems text,
    classics text,
    hobbies text,
    id_xbox character varying(64),
    id_ps character varying(64),
    id_nintendo character varying(64),
    image character varying,
    created_at timestamp without time zone NOT NULL,
    mod_for_boards integer[],
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.boards
(
    id serial NOT NULL,
    name character varying(64) NOT NULL,
    topic text,
    last_message timestamp without time zone,
    mods integer[],
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.msgs
(
    board_id integer NOT NULL,
    id serial NOT NULL,
    user_id integer NOT NULL,
    parent_id integer,
    parent_user_id integer,
    created_at timestamp without time zone NOT NULL,
    subject character varying(128) NOT NULL,
    body text,
    author_mod boolean,
    modified_at timestamp without time zone NOT NULL,
    PRIMARY KEY (id)
);

ALTER TABLE public.msgs
    ADD FOREIGN KEY (parent_id)
    REFERENCES public.msgs (id)
    NOT VALID;


ALTER TABLE public.msgs
    ADD FOREIGN KEY (user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.msgs
    ADD FOREIGN KEY (parent_user_id)
    REFERENCES public.users (id)
    NOT VALID;


ALTER TABLE public.msgs
    ADD FOREIGN KEY (board_id)
    REFERENCES public.boards (id)
    NOT VALID;

END;